run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.24'

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign

linters-settings:
  govet:
    check-shadowing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck 