version: '3'

tasks:
  setup:
    desc: Install required tools
    cmds:
      - |
        if ! command -v golangci-lint >/dev/null 2>&1; then
          echo "Installing golangci-lint from source..."
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi
      - |
        if ! command -v mockgen >/dev/null 2>&1; then
          echo "Installing mockgen..."
          go install go.uber.org/mock/mockgen@latest
        fi

  deps:
    desc: Install Go dependencies
    cmds:
      - go mod tidy
      - go mod download

  mocks:
    desc: Generate mocks for all interfaces
    deps: [setup, deps]
    cmds:
      - mockgen -source=internal/models/project_repository.go -destination=internal/models/mocks/project_repository_mock.go
      - mockgen -source=internal/service/project_service.go -destination=internal/service/mocks/project_service_mock.go
      - mockgen -source=internal/service/build_service.go -destination=internal/service/mocks/build_service_mock.go
      - mockgen -source=internal/service/test_suites_service.go -destination=internal/service/mocks/test_suites_service_mock.go
      - mockgen -source=internal/service/test_cases_service.go -destination=internal/service/mocks/test_cases_service_mock.go
      - mockgen -source=internal/service/build_executions_service.go -destination=internal/service/mocks/build_executions_service_mock.go
      - mockgen -source=internal/service/failures_service.go -destination=internal/service/mocks/failures_service_mock.go
      - mockgen -source=internal/service/junit_import_service.go -destination=internal/service/mocks/junit_import_service_mock.go

  lint:
    desc: Run golangci-lint
    deps: [setup, deps]
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  test-integration:
    desc: Run integration tests
    cmds:
      - go test -tags=integration ./...

  test-e2e:
    desc: Run end-to-end tests
    cmds:
      - go test ./tests/e2e

  ci:
    desc: Run full CI pipeline
    deps: [setup, deps, mocks, lint, test, cyclo]

  cyclo:
    desc: Analyze cyclomatic complexity in api/ (over 10)
    cmds:
      - gocyclo -over 10 .
