version: '3'

tasks:
  setup:
    desc: Install required tools
    cmds:
      - |
        if ! command -v golangci-lint >/dev/null 2>&1; then
          echo "Installing golangci-lint from source..."
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi
      - |
        if ! command -v mockgen >/dev/null 2>&1; then
          echo "Installing mockgen..."
          go install go.uber.org/mock/mockgen@latest
        fi
      - |
        if ! command -v gocyclo >/dev/null 2>&1; then
          echo "Installing gocyclo..."
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        fi

  deps:
    desc: Install Go dependencies
    cmds:
      - go mod tidy
      - go mod download

  mocks:
    desc: Generate mocks for hexagonal architecture domain interfaces
    deps: [setup, deps]
    cmds:
      # Generate all mocks in a single file to avoid package conflicts
      - mockgen -source=internal/domain/ports.go -destination=internal/domain/mocks.go -package=domain

  lint:
    desc: Run golangci-lint
    deps: [setup, deps]
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  test-integration:
    desc: Run integration tests
    cmds:
      - go test -tags=integration ./...

  test-e2e:
    desc: Run end-to-end tests
    cmds:
      - go test ./tests/e2e

  ci:
    desc: Run full CI pipeline
    deps: [setup, deps, mocks, lint, test, cyclo]

  cyclo:
    desc: Analyze cyclomatic complexity in api/ (over 10)
    deps: [setup]
    cmds:
      - gocyclo -over 10 .
