name: CI - API

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
    paths:
      - 'api/**'
      - '.github/workflows/ci-api.yml'

  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
    paths:
      - 'api/**'
      - '.github/workflows/ci-api.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Run tests
        run: go test ./...

