name: CI - API

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
    paths:
      - 'api/**'
      - '.github/workflows/ci-api.yml'

  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
    paths:
      - 'api/**'
      - '.github/workflows/ci-api.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install go-task
        run: |
          curl -sSLf https://github.com/go-task/task/releases/latest/download/task_linux_amd64.deb -o task.deb
          sudo dpkg -i task.deb

      - name: Setup tools
        run: task setup

      - name: Install dependencies
        run: task deps

      - name: Lint
        run: task lint

      - name: Test
        run: task test

