name: Frontend CI

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello from Frontend CI
        run: echo "✅ Workflow triggered by changes in frontend/ or ci-frontend.yml"
