name: Scripts CI

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
    paths:
      - 'scripts/**'
      - '.github/workflows/ci-scripts.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello from Scripts CI
        run: echo "✅ Workflow triggered by changes in scripts/ or ci-scripts.yml"
